# Generated by Django 4.2.5 on 2023-11-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
