# Generated by Django 4.2.5 on 2023-11-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_myclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
