# Generated by Django 4.2.5 on 2023-12-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0006_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('AP', 'Approval Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='AP', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.student')),
            ],
        ),
    ]
