# Generated by Django 4.2.5 on 2024-02-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0011_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
    ]
