# Generated by Django 4.2.5 on 2024-02-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0014_exceldata_email_exceldata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_number',
            field=models.IntegerField(default=6),
        ),
    ]
