# Generated by Django 4.2.5 on 2024-02-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0016_delete_class_alter_myclass_class_name'),
    ]

    operations = [
    ]
