# Generated by Django 4.2.5 on 2024-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0018_subject_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=255),
        ),
    ]
