# Generated by Django 4.2.5 on 2024-02-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0019_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=7, null=True),
        ),
    ]
