# Generated by Django 4.2.5 on 2024-02-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0020_subject_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
