# Generated by Django 4.2.5 on 2024-02-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0022_add_initial_sessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SessionTime',
        ),
    ]
