# Generated by Django 4.2.5 on 2024-02-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0023_rename_session_sessiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnew',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
