# Generated by Django 4.2.5 on 2024-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0024_studentnew_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnew',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentnew',
            name='subjects',
            field=models.ManyToManyField(to='AppOne.subject'),
        ),
    ]
