# Generated by Django 4.2.5 on 2024-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0025_studentnew_session_studentnew_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnew',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='AppOne.subject'),
        ),
    ]
