# Generated by Django 4.2.5 on 2024-02-28 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0026_alter_studentnew_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
