# Generated by Django 4.2.5 on 2024-02-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0029_alter_timetable_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
    ]
