# Generated by Django 4.2.5 on 2024-02-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0030_remove_timetable_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
