# Generated by Django 4.2.5 on 2024-02-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0031_rename_student_leaverequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='AppOne.studentnew'),
        ),
    ]
