# Generated by Django 4.2.5 on 2024-03-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0033_alter_leaverequest_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
