# Generated by Django 4.2.5 on 2024-03-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0036_alter_leaverequest_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentnew'),
        ),
        migrations.AlterField(
            model_name='studentnew',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning (06:00 - 08:00 AM)'), ('Evening', 'Evening (06:00 - 08:00 PM)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning (06:00 - 08:00 AM)'), ('Evening', 'Evening (06:00 - 08:00 PM)')], max_length=7, null=True),
        ),
    ]
