# Generated by Django 4.2.5 on 2024-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0037_alter_leaverequest_student_alter_studentnew_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnew',
            name='session_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
