# Generated by Django 4.2.5 on 2024-03-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0038_studentnew_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppOne.myclass'),
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='staff', to='AppOne.subject'),
        ),
        migrations.AlterField(
            model_name='studentnew',
            name='session_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
