# Generated by Django 4.2.5 on 2024-03-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0039_staff_class_name_staff_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='class_notes/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='AppOne.myclass')),
            ],
        ),
    ]
