# Generated by Django 4.2.5 on 2024-03-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0042_staffleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleaverequest',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppOne.myclass'),
        ),
    ]
