# Generated by Django 4.2.5 on 2024-03-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0043_staffleaverequest_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffleaverequest',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='AppOne.staff'),
        ),
        migrations.AlterField(
            model_name='staffleaverequest',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='AppOne.subject'),
        ),
    ]
