# Generated by Django 4.2.5 on 2024-03-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0044_remove_staffleaverequest_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_hour', models.BooleanField(default=False)),
                ('second_hour', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentnew')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.subject')),
            ],
        ),
    ]
