# Generated by Django 4.2.5 on 2024-03-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0046_googlemeetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemeetlink',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppOne.subject'),
        ),
    ]
