# Generated by Django 4.2.5 on 2024-03-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0047_googlemeetlink_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentnew')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.subject')),
            ],
        ),
    ]
