# Generated by Django 4.2.5 on 2024-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0052_alter_marks_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='month',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
