# Generated by Django 4.2.5 on 2024-04-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0054_alter_marks_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.studentnew')),
            ],
        ),
    ]
