# Generated by Django 4.2.5 on 2024-04-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0055_studentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppOne.subject'),
        ),
    ]
