# Generated by Django 4.2.5 on 2024-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0056_studentfeedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
    ]
