# Generated by Django 4.2.5 on 2024-04-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0057_feedbackquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackquestion',
            old_name='question',
            new_name='question_text',
        ),
    ]
