# Generated by Django 4.2.5 on 2024-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0058_rename_question_feedbackquestion_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackquestion',
            old_name='question_text',
            new_name='question',
        ),
    ]
