# Generated by Django 4.2.5 on 2024-04-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0061_feedbackstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='radio_options',
            field=models.JSONField(default=dict),
        ),
    ]
