# Generated by Django 4.2.5 on 2024-04-09 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0062_feedbackstudent_radio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='radio_options',
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=20)),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.feedbackquestion')),
                ('feedback_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppOne.feedbackstudent')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='questions',
            field=models.ManyToManyField(through='AppOne.SelectedOption', to='AppOne.feedbackquestion'),
        ),
    ]
